<?php

namespace common\models\setting;

use common\models\swp\Group;
use yii\base\Model;

/**
 * @property string $title
 * @property string $description
 */
class Base extends Model
{
    public $title;
    public $description;
    public $noModeration;

    public function init()
    {
        if ($material = Group::findOne(4)->material) {
            $this->title = $material->title;
            $this->description = $material->getValue(8);
            $this->noModeration = $material->getValue(18);
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}
